version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - log-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  
  loggerz-server:
    container_name: loggerz-server
    build:
      context: ./loggerz-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
       - ./loggerz-server:/usr/src/app/loggerz-server
       - /usr/src/app/loggerz-server/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo

  loggerz-app:
    container_name: loggerz-app
    build:
      context: ./loggerz-app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./loggerz-app:/usr/src/app/loggerz-app
      - /usr/src/app/loggerz-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - loggerz-server
  
volumes:
  log-data: